project:
  type: website
  title: "SMLP2023"
  execute-dir: project
  output-dir: _build/
  render:
  - about.qmd
  - AoGPlots.qmd
  - arrow.qmd
  - bootstrap.qmd
  - check_emotikon_transform.qmd
  - contrasts_fggk21.qmd
  - contrasts_kwdyz11.qmd
  - fggk21.qmd
  - glmm.qmd
  - index.qmd
  - kb07.qmd
  - kkl15.qmd
  - kwdyz11.qmd
  - largescaledesigned.qmd
  - mrk17.qmd
  - pkg.qmd
  - profiling.qmd
  - selection.qmd
  - shrinkageplot.qmd
  - singularity.qmd
  - sleepstudy.qmd
  - sleepstudy_speed.qmd
  - useful_packages.qmd

date: today
date-format: iso
jupyter: julia-1.9
execute:
  cache: true
  freeze: auto
number-sections: true

# editor_options:
#   chunk_output_type: console
filters:
  - code-fullscreen

format:
  html:
    # for more info, see
    # https://quarto.org/docs/output-formats/html-themes.html
    theme:
      light: [sandstone, theme.scss]
      dark: [darkly, theme-dark.scss]
    # defaults, can be overridden
    toc: true
    toc-depth: 2
    fig-width: 8
    fig-height: 6

website:
  title: "SMLP2023: Advanced Frequentist Track"
  site-url: https://RePsychLing.github.io/SMLP2023
  repo-url: https://github.com/RePsychLing/SMLP2023
  repo-actions: [edit, issue]
  # reader-mode: true
  navbar:
    background: primary
    # left:
    #   - text: "Home"
    #     href: index.qmd
    #   - about.qmd
    right:
      - icon: github
        href: https://github.com/RePsychLing/SMLP2023
  page-navigation: true
  back-to-top-navigation: true
  sidebar:
    style: "floating" # floating or docked
    search: true
    collapse-level: 1
    contents:
      - section: "Getting started with Julia"
        contents:
        - useful_packages.qmd
        - pkg.qmd
        - arrow.qmd
      - section: "Worked examples"
        contents:
        - sleepstudy.qmd
        - sleepstudy_speed.qmd
        - kwdyz11.qmd
        - kkl15.qmd
        - largescaledesigned.qmd
        - mrk17.qmd
      - section: "Contrast coding"
        contents:
        - contrasts_fggk21.qmd
        - contrasts_kwdyz11.qmd
      - glmm.qmd
      - section: "Bootstrap and profiling"
        contents:
        - bootstrap.qmd
        - profiling.qmd
        - kb07.qmd
      - section: "Visualizations and diagnostics"
        contents:
        - singularity.qmd
        - shrinkageplot.qmd
        - AoGPlots.qmd
